name: CI

on: [pull_request]

jobs:
  js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install node 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: install deps
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test
